project:
  type: website
  output-dir: docs

website:
  title: "ETC5523 - Communicating with Data Assignment 3"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ft-siddhi
  page-footer:
    center: "2025 Siddhi Jadhav"        
format:
  html:
    theme: flatly
    css: styles.css


